obstacle_range: 5
raytrace_range: 6
footprint: [[-0.6, -0.4], [-0.6, 0.4], [0.6, 0.4], [0.6, -0.4]]
#robot_radius: ir_of_robot
inflation_radius: 0.5

observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: base_footprint, data_type: LaserScan, topic: /base_scan, marking: true, clearing: true}