my_ur5:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  # Position Controllers ---------------------------------------
  my_ur5_shoulder_pan_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: my_ur5_shoulder_pan_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  my_ur5_shoulder_lift_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: my_ur5_shoulder_lift_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  my_ur5_elbow_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: my_ur5_elbow_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  my_ur5_wrist_1_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: my_ur5_wrist_1_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  my_ur5_wrist_2_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: my_ur5_wrist_2_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  my_ur5_wrist_3_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: my_ur5_wrist_3_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}